# Generated by Django 3.0.5 on 2020-04-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taxonomy', models.CharField(blank=True, max_length=255, null=True)),
                ('indoor', models.BooleanField()),
                ('outdoor', models.BooleanField()),
                ('sun', models.CharField(choices=[('SU', 'sun'), ('PS', 'part shade'), ('SH', 'shade')], max_length=2)),
                ('temperature_f', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('diameter_i', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('watering_frequency', models.DurationField()),
            ],
        ),
    ]
