# Generated by Django 3.0.5 on 2020-04-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('diameter', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('watering_frequency', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
