# Generated by Django 3.0.5 on 2020-04-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200409_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicPlant',
            new_name='Plant',
        ),
    ]
